set(SDK_PATH "/home/nino/SimplicityStudio/SDKs/gecko_sdk")
set(COPIED_SDK_PATH "gecko_sdk_4.4.1")

add_library(slc_SoC_Tag OBJECT
    "${SDK_PATH}/app/bluetooth/common/gatt_service_cte/sl_gatt_service_cte.c"
    "${SDK_PATH}/app/bluetooth/common/gatt_service_cte_adv/sl_gatt_service_cte_adv.c"
    "${SDK_PATH}/app/bluetooth/common/gatt_service_cte_adv/sl_gatt_service_cte_silabs.c"
    "${SDK_PATH}/app/bluetooth/common/in_place_ota_dfu/sl_bt_in_place_ota_dfu.c"
    "${SDK_PATH}/app/common/util/app_timer/app_timer.c"
    "${SDK_PATH}/hardware/board/src/sl_board_control_gpio.c"
    "${SDK_PATH}/hardware/board/src/sl_board_init.c"
    "${SDK_PATH}/platform/bootloader/api/btl_interface.c"
    "${SDK_PATH}/platform/bootloader/api/btl_interface_storage.c"
    "${SDK_PATH}/platform/bootloader/app_properties/app_properties.c"
    "${SDK_PATH}/platform/common/src/sl_assert.c"
    "${SDK_PATH}/platform/common/src/sl_slist.c"
    "${SDK_PATH}/platform/common/src/sl_syscalls.c"
    "${SDK_PATH}/platform/common/toolchain/src/sl_memory.c"
    "${SDK_PATH}/platform/Device/SiliconLabs/BGM22/Source/startup_bgm22.c"
    "${SDK_PATH}/platform/Device/SiliconLabs/BGM22/Source/system_bgm22.c"
    "${SDK_PATH}/platform/emdrv/nvm3/src/nvm3_default_common_linker.c"
    "${SDK_PATH}/platform/emdrv/nvm3/src/nvm3_hal_flash.c"
    "${SDK_PATH}/platform/emdrv/nvm3/src/nvm3_lock.c"
    "${SDK_PATH}/platform/emlib/src/em_burtc.c"
    "${SDK_PATH}/platform/emlib/src/em_cmu.c"
    "${SDK_PATH}/platform/emlib/src/em_core.c"
    "${SDK_PATH}/platform/emlib/src/em_dbg.c"
    "${SDK_PATH}/platform/emlib/src/em_emu.c"
    "${SDK_PATH}/platform/emlib/src/em_eusart.c"
    "${SDK_PATH}/platform/emlib/src/em_gpcrc.c"
    "${SDK_PATH}/platform/emlib/src/em_gpio.c"
    "${SDK_PATH}/platform/emlib/src/em_i2c.c"
    "${SDK_PATH}/platform/emlib/src/em_iadc.c"
    "${SDK_PATH}/platform/emlib/src/em_ldma.c"
    "${SDK_PATH}/platform/emlib/src/em_letimer.c"
    "${SDK_PATH}/platform/emlib/src/em_msc.c"
    "${SDK_PATH}/platform/emlib/src/em_prs.c"
    "${SDK_PATH}/platform/emlib/src/em_rmu.c"
    "${SDK_PATH}/platform/emlib/src/em_rtcc.c"
    "${SDK_PATH}/platform/emlib/src/em_se.c"
    "${SDK_PATH}/platform/emlib/src/em_system.c"
    "${SDK_PATH}/platform/emlib/src/em_timer.c"
    "${SDK_PATH}/platform/emlib/src/em_usart.c"
    "${SDK_PATH}/platform/emlib/src/em_wdog.c"
    "${SDK_PATH}/platform/radio/rail_lib/plugin/fem_util/sl_fem_util.c"
    "${SDK_PATH}/platform/radio/rail_lib/plugin/pa-conversions/pa_conversions_efr32.c"
    "${SDK_PATH}/platform/radio/rail_lib/plugin/rail_util_power_manager_init/sl_rail_util_power_manager_init.c"
    "${SDK_PATH}/platform/radio/rail_lib/plugin/rail_util_pti/sl_rail_util_pti.c"
    "${SDK_PATH}/platform/security/sl_component/se_manager/src/sl_se_manager.c"
    "${SDK_PATH}/platform/security/sl_component/se_manager/src/sl_se_manager_attestation.c"
    "${SDK_PATH}/platform/security/sl_component/se_manager/src/sl_se_manager_cipher.c"
    "${SDK_PATH}/platform/security/sl_component/se_manager/src/sl_se_manager_entropy.c"
    "${SDK_PATH}/platform/security/sl_component/se_manager/src/sl_se_manager_hash.c"
    "${SDK_PATH}/platform/security/sl_component/se_manager/src/sl_se_manager_key_derivation.c"
    "${SDK_PATH}/platform/security/sl_component/se_manager/src/sl_se_manager_key_handling.c"
    "${SDK_PATH}/platform/security/sl_component/se_manager/src/sl_se_manager_signature.c"
    "${SDK_PATH}/platform/security/sl_component/se_manager/src/sl_se_manager_util.c"
    "${SDK_PATH}/platform/security/sl_component/sl_cryptoacc_library/src/ba414ep_config.c"
    "${SDK_PATH}/platform/security/sl_component/sl_cryptoacc_library/src/ba431_config.c"
    "${SDK_PATH}/platform/security/sl_component/sl_cryptoacc_library/src/cryptodma_internal.c"
    "${SDK_PATH}/platform/security/sl_component/sl_cryptoacc_library/src/cryptolib_types.c"
    "${SDK_PATH}/platform/security/sl_component/sl_cryptoacc_library/src/sx_aes.c"
    "${SDK_PATH}/platform/security/sl_component/sl_cryptoacc_library/src/sx_blk_cipher.c"
    "${SDK_PATH}/platform/security/sl_component/sl_cryptoacc_library/src/sx_dh_alg.c"
    "${SDK_PATH}/platform/security/sl_component/sl_cryptoacc_library/src/sx_ecc_curves.c"
    "${SDK_PATH}/platform/security/sl_component/sl_cryptoacc_library/src/sx_ecc_keygen_alg.c"
    "${SDK_PATH}/platform/security/sl_component/sl_cryptoacc_library/src/sx_ecdsa_alg.c"
    "${SDK_PATH}/platform/security/sl_component/sl_cryptoacc_library/src/sx_hash.c"
    "${SDK_PATH}/platform/security/sl_component/sl_cryptoacc_library/src/sx_math.c"
    "${SDK_PATH}/platform/security/sl_component/sl_cryptoacc_library/src/sx_memcmp.c"
    "${SDK_PATH}/platform/security/sl_component/sl_cryptoacc_library/src/sx_memcpy.c"
    "${SDK_PATH}/platform/security/sl_component/sl_cryptoacc_library/src/sx_primitives.c"
    "${SDK_PATH}/platform/security/sl_component/sl_cryptoacc_library/src/sx_rng.c"
    "${SDK_PATH}/platform/security/sl_component/sl_cryptoacc_library/src/sx_trng.c"
    "${SDK_PATH}/platform/security/sl_component/sl_mbedtls_support/src/cryptoacc_aes.c"
    "${SDK_PATH}/platform/security/sl_component/sl_mbedtls_support/src/cryptoacc_gcm.c"
    "${SDK_PATH}/platform/security/sl_component/sl_mbedtls_support/src/mbedtls_ccm.c"
    "${SDK_PATH}/platform/security/sl_component/sl_mbedtls_support/src/mbedtls_cmac.c"
    "${SDK_PATH}/platform/security/sl_component/sl_mbedtls_support/src/mbedtls_ecdsa_ecdh.c"
    "${SDK_PATH}/platform/security/sl_component/sl_mbedtls_support/src/sl_mbedtls.c"
    "${SDK_PATH}/platform/security/sl_component/sl_mbedtls_support/src/sl_psa_crypto.c"
    "${SDK_PATH}/platform/security/sl_component/sl_mbedtls_support/src/sli_psa_crypto.c"
    "${SDK_PATH}/platform/security/sl_component/sl_protocol_crypto/src/sli_protocol_crypto_radioaes.c"
    "${SDK_PATH}/platform/security/sl_component/sl_protocol_crypto/src/sli_radioaes_management.c"
    "${SDK_PATH}/platform/security/sl_component/sl_psa_driver/src/cryptoacc_management.c"
    "${SDK_PATH}/platform/security/sl_component/sl_psa_driver/src/sl_psa_its_nvm3.c"
    "${SDK_PATH}/platform/security/sl_component/sl_psa_driver/src/sli_cryptoacc_driver_trng.c"
    "${SDK_PATH}/platform/security/sl_component/sl_psa_driver/src/sli_cryptoacc_transparent_driver_aead.c"
    "${SDK_PATH}/platform/security/sl_component/sl_psa_driver/src/sli_cryptoacc_transparent_driver_cipher.c"
    "${SDK_PATH}/platform/security/sl_component/sl_psa_driver/src/sli_cryptoacc_transparent_driver_hash.c"
    "${SDK_PATH}/platform/security/sl_component/sl_psa_driver/src/sli_cryptoacc_transparent_driver_key_derivation.c"
    "${SDK_PATH}/platform/security/sl_component/sl_psa_driver/src/sli_cryptoacc_transparent_driver_key_management.c"
    "${SDK_PATH}/platform/security/sl_component/sl_psa_driver/src/sli_cryptoacc_transparent_driver_mac.c"
    "${SDK_PATH}/platform/security/sl_component/sl_psa_driver/src/sli_cryptoacc_transparent_driver_signature.c"
    "${SDK_PATH}/platform/security/sl_component/sl_psa_driver/src/sli_psa_driver_common.c"
    "${SDK_PATH}/platform/security/sl_component/sl_psa_driver/src/sli_psa_driver_init.c"
    "${SDK_PATH}/platform/security/sl_component/sl_psa_driver/src/sli_psa_trng.c"
    "${SDK_PATH}/platform/security/sl_component/sl_psa_driver/src/sli_se_version_dependencies.c"
    "${SDK_PATH}/platform/service/device_init/src/sl_device_init_dcdc_s2.c"
    "${SDK_PATH}/platform/service/device_init/src/sl_device_init_emu_s2.c"
    "${SDK_PATH}/platform/service/device_init/src/sl_device_init_hfxo_s2.c"
    "${SDK_PATH}/platform/service/device_init/src/sl_device_init_lfrco.c"
    "${SDK_PATH}/platform/service/device_init/src/sl_device_init_lfxo_s2.c"
    "${SDK_PATH}/platform/service/device_init/src/sl_device_init_nvic.c"
    "${SDK_PATH}/platform/service/mpu/src/sl_mpu.c"
    "${SDK_PATH}/platform/service/power_manager/src/sl_power_manager.c"
    "${SDK_PATH}/platform/service/power_manager/src/sl_power_manager_debug.c"
    "${SDK_PATH}/platform/service/power_manager/src/sl_power_manager_hal_s2.c"
    "${SDK_PATH}/platform/service/sleeptimer/src/sl_sleeptimer.c"
    "${SDK_PATH}/platform/service/sleeptimer/src/sl_sleeptimer_hal_burtc.c"
    "${SDK_PATH}/platform/service/sleeptimer/src/sl_sleeptimer_hal_prortc.c"
    "${SDK_PATH}/platform/service/sleeptimer/src/sl_sleeptimer_hal_rtcc.c"
    "${SDK_PATH}/platform/service/sleeptimer/src/sl_sleeptimer_hal_timer.c"
    "${SDK_PATH}/platform/service/system/src/sl_system_init.c"
    "${SDK_PATH}/platform/service/system/src/sl_system_process_action.c"
    "${SDK_PATH}/protocol/bluetooth/src/sl_apploader_util_s2.c"
    "${SDK_PATH}/protocol/bluetooth/src/sl_bt_stack_init.c"
    "${SDK_PATH}/protocol/bluetooth/src/sli_bt_accept_list_config.c"
    "${SDK_PATH}/protocol/bluetooth/src/sli_bt_advertiser_config.c"
    "${SDK_PATH}/protocol/bluetooth/src/sli_bt_connection_config.c"
    "${SDK_PATH}/protocol/bluetooth/src/sli_bt_dynamic_gattdb_config.c"
    "${SDK_PATH}/protocol/bluetooth/src/sli_bt_l2cap_config.c"
    "${SDK_PATH}/protocol/bluetooth/src/sli_bt_pawr_advertiser_config.c"
    "${SDK_PATH}/protocol/bluetooth/src/sli_bt_periodic_adv_config.c"
    "${SDK_PATH}/protocol/bluetooth/src/sli_bt_periodic_advertiser_config.c"
    "${SDK_PATH}/protocol/bluetooth/src/sli_bt_sync_config.c"
    "${SDK_PATH}/util/silicon_labs/silabs_core/memory_manager/sl_malloc.c"
    "${SDK_PATH}/util/third_party/mbedtls/library/cipher.c"
    "${SDK_PATH}/util/third_party/mbedtls/library/cipher_wrap.c"
    "${SDK_PATH}/util/third_party/mbedtls/library/constant_time.c"
    "${SDK_PATH}/util/third_party/mbedtls/library/platform.c"
    "${SDK_PATH}/util/third_party/mbedtls/library/platform_util.c"
    "${SDK_PATH}/util/third_party/mbedtls/library/psa_crypto.c"
    "${SDK_PATH}/util/third_party/mbedtls/library/psa_crypto_aead.c"
    "${SDK_PATH}/util/third_party/mbedtls/library/psa_crypto_cipher.c"
    "${SDK_PATH}/util/third_party/mbedtls/library/psa_crypto_client.c"
    "${SDK_PATH}/util/third_party/mbedtls/library/psa_crypto_driver_wrappers_no_static.c"
    "${SDK_PATH}/util/third_party/mbedtls/library/psa_crypto_ecp.c"
    "${SDK_PATH}/util/third_party/mbedtls/library/psa_crypto_ffdh.c"
    "${SDK_PATH}/util/third_party/mbedtls/library/psa_crypto_hash.c"
    "${SDK_PATH}/util/third_party/mbedtls/library/psa_crypto_mac.c"
    "${SDK_PATH}/util/third_party/mbedtls/library/psa_crypto_pake.c"
    "${SDK_PATH}/util/third_party/mbedtls/library/psa_crypto_rsa.c"
    "${SDK_PATH}/util/third_party/mbedtls/library/psa_crypto_se.c"
    "${SDK_PATH}/util/third_party/mbedtls/library/psa_crypto_slot_management.c"
    "${SDK_PATH}/util/third_party/mbedtls/library/psa_crypto_storage.c"
    "${SDK_PATH}/util/third_party/mbedtls/library/psa_util.c"
    "${SDK_PATH}/util/third_party/mbedtls/library/threading.c"
    "../app.c"
    "../autogen/gatt_db.c"
    "../autogen/sl_bluetooth.c"
    "../autogen/sl_board_default_init.c"
    "../autogen/sl_device_init_clocks.c"
    "../autogen/sl_event_handler.c"
    "../autogen/sl_power_manager_handler.c"
    "../main.c"
    "../sl_gatt_service_device_information.c"
)

target_include_directories(slc_SoC_Tag PUBLIC
   "../config"
   "../config/btconf"
   "../autogen"
   "../."
    "${SDK_PATH}/platform/Device/SiliconLabs/BGM22/Include"
    "${SDK_PATH}/app/common/util/app_assert"
    "${SDK_PATH}/app/common/util/app_timer"
    "${SDK_PATH}/protocol/bluetooth/inc"
    "${SDK_PATH}/platform/common/inc"
    "${SDK_PATH}/protocol/bluetooth/bgcommon/inc"
    "${SDK_PATH}/protocol/bluetooth/bgstack/ll/inc"
    "${SDK_PATH}/hardware/board/inc"
    "${SDK_PATH}/platform/bootloader"
    "${SDK_PATH}/platform/bootloader/api"
    "${SDK_PATH}/platform/CMSIS/Core/Include"
    "${SDK_PATH}/platform/security/sl_component/sl_cryptoacc_library/include"
    "${SDK_PATH}/platform/security/sl_component/sl_cryptoacc_library/src"
    "${SDK_PATH}/platform/service/device_init/inc"
    "${SDK_PATH}/platform/emdrv/common/inc"
    "${SDK_PATH}/platform/emlib/inc"
    "${SDK_PATH}/platform/radio/rail_lib/plugin/fem_util"
    "${SDK_PATH}/app/bluetooth/common/gatt_service_cte"
    "${SDK_PATH}/app/bluetooth/common/gatt_service_cte_adv"
    "${SDK_PATH}/app/bluetooth/common/gatt_service_device_information"
    "${SDK_PATH}/app/bluetooth/common/in_place_ota_dfu"
    "${SDK_PATH}/platform/security/sl_component/sl_mbedtls_support/config"
    "${SDK_PATH}/platform/security/sl_component/sl_mbedtls_support/config/preset"
    "${SDK_PATH}/platform/security/sl_component/sl_mbedtls_support/inc"
    "${SDK_PATH}/util/third_party/mbedtls/include"
    "${SDK_PATH}/util/third_party/mbedtls/library"
    "${SDK_PATH}/platform/service/mpu/inc"
    "${SDK_PATH}/platform/emdrv/nvm3/inc"
    "${SDK_PATH}/platform/service/power_manager/inc"
    "${SDK_PATH}/platform/security/sl_component/sl_psa_driver/inc"
    "${SDK_PATH}/platform/radio/rail_lib/common"
    "${SDK_PATH}/platform/radio/rail_lib/protocol/ble"
    "${SDK_PATH}/platform/radio/rail_lib/protocol/ieee802154"
    "${SDK_PATH}/platform/radio/rail_lib/protocol/wmbus"
    "${SDK_PATH}/platform/radio/rail_lib/protocol/zwave"
    "${SDK_PATH}/platform/radio/rail_lib/chip/efr32/efr32xg2x"
    "${SDK_PATH}/platform/radio/rail_lib/protocol/sidewalk"
    "${SDK_PATH}/platform/radio/rail_lib/plugin/pa-conversions"
    "${SDK_PATH}/platform/radio/rail_lib/plugin/pa-conversions/efr32xg22"
    "${SDK_PATH}/platform/radio/rail_lib/plugin/rail_util_power_manager_init"
    "${SDK_PATH}/platform/radio/rail_lib/plugin/rail_util_pti"
    "${SDK_PATH}/platform/security/sl_component/se_manager/inc"
    "${SDK_PATH}/platform/security/sl_component/se_manager/src"
    "${SDK_PATH}/util/silicon_labs/silabs_core/memory_manager"
    "${SDK_PATH}/platform/common/toolchain/inc"
    "${SDK_PATH}/platform/service/system/inc"
    "${SDK_PATH}/platform/service/sleeptimer/inc"
    "${SDK_PATH}/platform/security/sl_component/sl_protocol_crypto/src"
)

target_compile_definitions(slc_SoC_Tag PUBLIC
    "BGM220PC22HNA=1"
    "SL_APP_PROPERTIES=1"
    "BOOTLOADER_APPLOADER=1"
    "HARDWARE_BOARD_DEFAULT_RF_BAND_2400=1"
    "HARDWARE_BOARD_SUPPORTS_1_RF_BAND=1"
    "HARDWARE_BOARD_SUPPORTS_RF_BAND_2400=1"
    "SL_BOARD_NAME=\"BRD4314A\""
    "SL_BOARD_REV=\"A02\""
    "SL_COMPONENT_CATALOG_PRESENT=1"
    "MBEDTLS_CONFIG_FILE=<sl_mbedtls_config.h>"
    "MBEDTLS_PSA_CRYPTO_CONFIG_FILE=<psa_crypto_config.h>"
    "SL_RAIL_LIB_MULTIPROTOCOL_SUPPORT=0"
    "SL_RAIL_UTIL_PA_CONFIG_HEADER=<sl_rail_util_pa_config.h>"
    "SLI_RADIOAES_REQUIRES_MASKING=1"
)

target_link_libraries(slc_SoC_Tag PUBLIC
    "-Wl,--start-group"
    "gcc"
    "c"
    "m"
    "nosys"
   "${SDK_PATH}/protocol/bluetooth/bgcommon/lib/libbgcommon_efr32xg22_gcc_release.a"
   "${SDK_PATH}/protocol/bluetooth/bgstack/ll/lib/libbluetooth_controller_efr32xg22_gcc_release.a"
   "${SDK_PATH}/protocol/bluetooth/lib/libbluetooth_host_efr32xg22_gcc_release.a"
   "${SDK_PATH}/platform/emdrv/nvm3/lib/libnvm3_CM33_gcc.a"
   "${SDK_PATH}/platform/radio/rail_lib/autogen/librail_release/librail_config_bgm220pc22hna_gcc.a"
   "${SDK_PATH}/platform/radio/rail_lib/autogen/librail_release/librail_module_efr32xg22_gcc_release.a"
    "-Wl,--end-group"
)
target_compile_options(slc_SoC_Tag PUBLIC
    $<$<COMPILE_LANGUAGE:C>:-mcpu=cortex-m33>
    $<$<COMPILE_LANGUAGE:C>:-mthumb>
    $<$<COMPILE_LANGUAGE:C>:-mfpu=fpv5-sp-d16>
    $<$<COMPILE_LANGUAGE:C>:-mfloat-abi=hard>
    $<$<COMPILE_LANGUAGE:C>:-Wall>
    $<$<COMPILE_LANGUAGE:C>:-Wextra>
    $<$<COMPILE_LANGUAGE:C>:-Os>
    $<$<COMPILE_LANGUAGE:C>:-fdata-sections>
    $<$<COMPILE_LANGUAGE:C>:-ffunction-sections>
    $<$<COMPILE_LANGUAGE:C>:-fomit-frame-pointer>
    "$<$<COMPILE_LANGUAGE:C>:SHELL:-imacros sl_gcc_preinclude.h>"
    $<$<COMPILE_LANGUAGE:C>:-mcmse>
    $<$<COMPILE_LANGUAGE:C>:--specs=nano.specs>
    $<$<COMPILE_LANGUAGE:C>:-g>
    $<$<COMPILE_LANGUAGE:CXX>:-mcpu=cortex-m33>
    $<$<COMPILE_LANGUAGE:CXX>:-mthumb>
    $<$<COMPILE_LANGUAGE:CXX>:-mfpu=fpv5-sp-d16>
    $<$<COMPILE_LANGUAGE:CXX>:-mfloat-abi=hard>
    $<$<COMPILE_LANGUAGE:CXX>:-fno-rtti>
    $<$<COMPILE_LANGUAGE:CXX>:-fno-exceptions>
    $<$<COMPILE_LANGUAGE:CXX>:-Wall>
    $<$<COMPILE_LANGUAGE:CXX>:-Wextra>
    $<$<COMPILE_LANGUAGE:CXX>:-Os>
    $<$<COMPILE_LANGUAGE:CXX>:-fdata-sections>
    $<$<COMPILE_LANGUAGE:CXX>:-ffunction-sections>
    $<$<COMPILE_LANGUAGE:CXX>:-fomit-frame-pointer>
    "$<$<COMPILE_LANGUAGE:CXX>:SHELL:-imacros sl_gcc_preinclude.h>"
    $<$<COMPILE_LANGUAGE:CXX>:-mcmse>
    $<$<COMPILE_LANGUAGE:CXX>:--specs=nano.specs>
    $<$<COMPILE_LANGUAGE:CXX>:-g>
    $<$<COMPILE_LANGUAGE:ASM>:-mcpu=cortex-m33>
    $<$<COMPILE_LANGUAGE:ASM>:-mthumb>
    $<$<COMPILE_LANGUAGE:ASM>:-mfpu=fpv5-sp-d16>
    $<$<COMPILE_LANGUAGE:ASM>:-mfloat-abi=hard>
    "$<$<COMPILE_LANGUAGE:ASM>:SHELL:-imacros sl_gcc_preinclude.h>"
    "$<$<COMPILE_LANGUAGE:ASM>:SHELL:-x assembler-with-cpp>"
)

set(post_build_command )
set_property(TARGET slc_SoC_Tag PROPERTY C_STANDARD 99)
set_property(TARGET slc_SoC_Tag PROPERTY CXX_STANDARD 11)
set_property(TARGET slc_SoC_Tag PROPERTY CXX_EXTENSIONS OFF)

target_link_options(slc_SoC_Tag INTERFACE
    -mcpu=cortex-m33
    -mthumb
    -mfpu=fpv5-sp-d16
    -mfloat-abi=hard
    -T${CMAKE_CURRENT_LIST_DIR}/../autogen/linkerfile.ld
    --specs=nano.specs
    "SHELL:-Xlinker -Map=$<TARGET_FILE_DIR:SoC_Tag>/SoC_Tag.map"
    -Wl,--gc-sections
    -Wl,--no-warn-rwx-segments
)

# BEGIN_SIMPLICITY_STUDIO_METADATA=eJztvQmT3DaaLfpXHBUTL+7iSlZlSbKta3eHLKl7dK/U0lPJM29iNMFAkshMurg9klmLO/q/PwDcSRDrB6bmxcy4JWUmcM7Bh3378PeLT58//u+3r7/4nz9+/HLx8uLvXy8+v33/6su7f3nrD3/6evHy68Vm8/XiHxffd3FuP/72+fXbWxLt5z8/JvF397gooyz95evF9ebq68V3OA2yMEoP5Ivfvvzl8sevF3/+09f057zIfsdB9R35O8dF9XQbkL9JmOb7rxck0Hff/bzP4hAX36UooT+iU5UdcNr8SH+OYtz+eEBV5Ye7TUBIT0VEvqG/vvSOWYK9NEoz7wMqohQXmf/m4yv/1/dvvdvstf8FHbwG1xtAeCKKoz3FcYGijP1dfMJVllVHm6RMceRkFoma4iySZagI/RDv0Smu/CiNKtskcgGX6FGex1GAKlI8/eopx5ZJ5sFxqT9/eeu/zpI8S3FalTasc6SltAZtKJ8oRHF2sEwsF2+JPMT3UYBZfvhBnAV3pWU+8wGX6PE91XlEaRjjwjLdMyw1UrvkzrAWSCM/2eGwikuSPek+OvgNhl2aRaiqQqoCpeU+KxJHkrj4S1mTZw+48BOUogP5GyaLFjEXLZSXCDib+IhCAbtTFFdR6kDIMjJXUByld7ig32zi0Jx9AsOl2gRF0Mii/zQnmwHVdD979SiFN2KpQw8GLKNfdxX9vfuVN9ooccGavqDCGzK80hdfK/BqKo+P6fEFkNzMY0QCZhXyw/0JQgAfc0EAU1vHPxWso920JgMwAx9YJGVgOB+F9y4ypMftyvKweM0btwQnWfHUFkuDitzo4UEtNagz0WUUo10JIkKOrazKiRyJjvQ+uekGpNYCFtC4zKw3KJ7yKrPn5WKpjPbifREA8EtQVZSEQRiAC5mASidVIAJ4aOIZFglXFVkMw76AqJT2lEzl6fQI3AxzYK4eMkXzUUmqL0Bd5GItWaGMMc6rKCFjQ4i0c+HUhrsQ9EuIi2WAzsXH/TxMERDiqrVPjy6ap0eV1qlAUeyfKvIHyUoQEUuIi3WhWW2LMEBfvYgnbxnIGIfGKoGKpwRYpVzgBKaELmMqlIpRLavXOmALiYhAxUpHF7XnqF17ELRdkIx/V8VEbEVmmrTpCfY21FyspVTvcVJrhEgxB4zLi5M42pFABSYZtTsd7MkFiEspHy/4WE5sZlgy1qaAQpLPIOWrB1FCaip/t6PAKExIDUoOV5s8PegLZNjeDIZrmD7UNQzZtRLZFoZsOyQTmfuAg7vML8M7/9nm2eZ6adWGjD8quvQ4WrcZhXjDsnrw+yzEbRRHpCS8JzPbUbBZwF//+mG7nQSZo2WnYsLHWcIon8qKtAC7Q7LdClY/b6OE7mtE1dNtdQoj8sWb/1N6nW28NvlenUpvkBSPqfVqOd6Uz5PIq1BRnfIV9U0JpwInKy8Lxn+XBvEplFqfsVzlwXZ7TJGgRbFPXiPImzFKMoCF9xEW7VABq2vZlJTtTgVKVtTW8amqq4J11dV8SuqC5LSitoZNTRlbZkLBmrYbcSqppAs/Kwps6dS0Ecx0n60pr2dUU5iQuTougyIiZhftyIILnRGr6c3jeE2VDZ2SNrxqTcYaNRmfStKhrimuI1TSty+LYM1a0vEpqTvkQbFmE9PxKaqL1jRdS6eszc+zVYveiFNJ5XG/bunr+BTVPa4r7lFdW7Rds140bGrK0KqjgpZOTVuAgqPoiBu4uo5QSV9M+uYV1bV0ytoed2jNkcqQUksj3R6O0lUnbTxqNc2Y7WGtKbVnVFO4cisda7XS8bqtdKzTSiflmk1hw6akLA/XXDVo2NSUFWtW24ZNVZlfRocUxSsrHLIqKS2qVZcOWjolbeWqc7VSY65WPpXiXSxwcR2hkr61+wm9XuK0djdx0usn1p6I683DH0LhbQRocS2dRBtOmh26VaSN2GQbI8N9lDXETQmV9kU4X86+mn8xPS2dJFkq2jeL0mC2XzbewUVVlkQgPUKtxiOU3gjXE/Lj9AQy3Bizt6hi7gPdu2wu4MFrmKKLtdRH5RzkQ4cr5q9jwfP3uGL+Mo5KB8nvYCXsFapOIEO3CX2H64kq+qzeloW03tb5CrDv2ygmlN4IV2IxMkBBcSy6qWaoYIisUmbgBbSwenlWZVkcHFGUik8ozLN26ZICYMo6bW0aewZP1i0pdCqL1ywKfIBtW/uENDVsRjTrffm2dS5JRcshCMgkDkf1QMKlpjmTNN+1hyO7LKviDJFvREOS8TlYUSs3DglRG3qFk+O43pxLr/KjPBIlZXSIETwlkTfDFzSc4wOVZZUV6OBc05BHoG14R3yQHQAVYyJumUhiOVwUGZlbwtRWjsVG+Kq56EjLCF+5ROWoKGEWI4QFqqfRLuuupQ14JNoKXGJ6SQPmOApH1JhA2KbJmvfXH27f3Ypa9tdZMT3Wp3j2b2SXICmjkjlQiMT+CJTtwpR7VF43Z5+TCPvqOjjgVHFR0uKEcaKo+oNdMsOPIJMmjpwxgYJ1DjALy4uWOfBXksdK6JH5ILm5caVkiC9UkuQnHxXJ/Y+OlIzw4cdyJQ6I5upJVN+Hbk4kc564P0Pox9GuQMWT7JA2b540bUHRs+tnOO98DNgbuk32yIWLx5PPJlJzAbIVXfTs5vqsekf0ErU1CD0UyPq2FMVn0MwXoaScXqKhnoZA5g5GskcKZOvWj+x49/pSe2K5wl185wdRfhQ6hHEodMwv1xsefRSfo6qNuOU6MYlO8O/PVQDG/Gp67/DTAafns+9cg4rusETnlDygl6s9olLk1c6h0JZZrjFBQs97DjW2zAoacRIk+ZlUdtxqOnOQdV8znTlnRZinMy+iJKqis7VWY3653iI9U31viOUKq7NJrNQ00qHutcINX5dD7WueOyGB3pvzyr3RUzuYSJxH71iAzkzmLHpH9PozmfU180VIlOcopO6AzyB3wKw1L1hf6YxfqrfAB5BdBW2hLbHZ3elI7e50u6zp48eK6ImydO3ERt16GVeJ8uw9xPtzKZ9q0FxxOLfqToXaqsN55PbkOi0M4FklM81cKcprEWeT3fMraIW5bWQoVOnu0XjV4mxixxq0V07OqnusQ2f15IyyBxIUFNPt9HOWjo5fcbXnbEpbdgWdDxKXXq6VPkzdgC1rZWtEZ1PasiuvUJ1PacevvEp1Vq0593ydcKXqbHrHGtRWq84mtlCd8VVnlVkt6FS9a8Hbom49z5WnnLoqkG1QB2Nf9UuWGjzGQNKCyWSodqDu0nSTlPTe9Za1yDJ8EDVL0iinB4tSkLMnNqmYSFFIBHXV/S3kA0+H2aKAwkGJXorTNeZpctuz5j210iSaVnnXO+E8qTN2idrOTWaQrK51wq2qNEHB+aQ25Ipa64E++dPt7qJI8ViCctk9nKE8zNilTaHfP1pwjkZhzK7YcJ9N7pTeePlWo6Ves2Nqb6701JIcIS0kmYSv2/9TkQNeWX0MkrMoHPDKFJIG8TwSB8SymndE12fROCSWa9w+f3EulQNquc7n19tz6RxQS3QezlRzDso1Z9x/nKGhHLPr9V7ry53Sq1n3HsUnx8smAuv27JBTfIocFtH95IoiL7DKrKo2rPOzO73q0XBE8eROG7xGkD0j60zthF5PdLPNdj7ZvQAF4SVur/H4Ic5xGuI0ALrBqiNfIEN5LlO/fpLQ9ZUV1S/xK9i+j9rk3Dlq56IIrQSwR1tzVNDHbRsc5weChYkRCLJN2Ap3CnSTpn7NQIaEMAq/qaS1gmwT5no5STddaitMUpg7/ERaTPLvemX2W0rhXBpEYs/TyhtIs00s85ZYnQoQfwdg6RypUhucR1Xp09dO103HjBp2HWz8bFCJOIEm1mgP0hKrnsoKh5BX/FXMQics5KMn0jHPUE6p/VYSItMiTQw78LK26o6UU3n4JVJpurFiKhYF6M2T9pi1I25n7WLpQwkWc6WVEyCQYTJXWlH9Er/xXGllyy+KMO7r96c0cH/oXZiURTnGiXJ/qlw5QYtHy81X5nD7zCrIspzf4zkcH3Ucnd/AEat8HNeHZ8+MnkdqR62l1/l0XaRYY2I+jIbpk+xOb9eKRA/YtVQ7XvERSVZe2xlGWm3uLFJuMEueRj+iNIwjp0uHshQMJWjpX2OWKxKvOZ8dxERVhanP3PMVnYkCtRFsGzkrnV4snermcusr9nekX09wdV7tYxUuD9gM+uk10tu6gh6xatUKwCeL9NVqvFo0jud6xCrSrHz7cT4UOo/gllqv9q4w3Z+KXuTXsnS3xET6uXOVkZkGPduv4EhAaHsNHwKT4fORCHDvuUFk+qkEPf1nVW6o2bVrBKFmZb8I3BnLeUQP2PXnS+eRrHqDUjRVOY/yuQjz+dL5UjCUYDhfOo/4Eb/xfOk82icKQA/rFVmVBVl7ExDqxN4Y1S8QsYjr60YT0v6EmUCMwnCkDb7aBv5CMhZ0qOxdjRHdLnCrZYLiUJCX5nOoX9BhWhENPEUX9H00kaPo+uk2dvRT7Cda5WWZAZgfxFlwBzR/YKnwBuhtY8cnFDr/nsQKA5h3rxVFtnQ6EjHM05uKCjH/6U2RQKgX1xUVLr24LpII9sqlosbFRy7FIle149KbyCKJ6T3Mg4SKEls6qRN9pRGHrB3wyy1MFz1PW7OYvcCo2Rqsq7Mn1G0T1tU5YNRvGdaT2fHptgzrWjM2syarsOupbOmk7YP8lbAkPwE8DpifIFNP4DpHDTWyfkOo9CJgDjrCoLLbW8s5ZzRhlD959sBOkfOOohjk1AgOMs9GwN3Z3CmbrE6NIpAivzsB7Xariuw59aQeUQzcUClo7UklYqNJxJytqwGtLS3LFdC6qdDj8uYsde2d0CmbSeleVWTPqVdgXKvk0AE0nfUj6PZtZvOYOtwt1doQNezgieEhiawoNcHzIgtwSV1nwZ1PEaib07mpx0NjABa9Jk3tivGYxMzirtXN6SAqRoxxXkUJxICixwItfR1q/wL2kEeaWV1o1kkWVQA6PBfJGxFq6iS5TWKuqrSn1NS6O60ttWPUVLpq6RwzSrvZcUTQ5mQqkkfmqPnu66qbBLVt5IhHw9ZOZU2J9Bts2f4GTsLiXrS7Ud/VstzYwFBPSjO57TPw1EZ44TFpk76MXvu0TCiFoEcK0QnGw1CdXorKUjuFF5ZTdovVjQYlbv+AU1zALHbz7DCAl2sBahF5Orjt34IGfx8DneBZUNITyPXQ3T5XUlpsB9sOw0rQXCX14yi9g+mYB4mhfZ2YTCfPHWkbESjmuSMpLbZ+nsfRTpznJACjeP3h5oY9lY1Ak0DgPR6Fi/52mlZp8R/3pAncaJlpYdk3RPWE5EECsjw/om4wJcQZzIWfMXPGu8UzpQ53ICvHI+YGU0yMHRgbqxgbn0pUgKxQjbk7WDH9IQ8K+BLeocrII5DNzAl3xNmxnFJHW/hUN5gSYhQ6YG5AxdQxfQ4JmroFlVBjsOn8mB0vTNqnApIS3uoNppg4L0AOhI6IG0wxceGgRStUWjSoZbsxM3dpbkpdwvdbpUKvVa/6wlN3sGJ6N1VLsWK56b4Ue6+HMIMfL7SgnmjwqbBewR9MgkwCqVq2JDNAlYzpjhHIo1Aj7hZUPo4FZ+ad++QQs5PPCGh9aMw/gBbIoAuLLmwwxhXbAZUlLuBt0MOK6XcnkIPVk1LPOTs9n8dAOd8a5/2CS61ZP4gS6rEHnH+AKxbQ+KECFzDAVZhIwpufd72JRw27KjqRsLwmypvTQitoMOVzWmhi7oH7hTktOHcHq0LvqumfoatMsKFFdKgKE2x47ohzEp83wYZmbjAVJtjgzIh3E4Y7wYamjrmPGC9NsMHZ8dKOKGeCDU3eYEqJXVX1MbR8ng/Nn/Me/OXN88GHGCqtPJuSgzM3oNJ5PjRxqTCoKB2YulQxdflUAj2UPObuYJXWNxzQN7Aq9M5Gc3N4leUWaBWKzaybkZXiwIqtjEBzt6DC5RbZXh+7uyza6ytQFPvzvc/ptY34dIimJ3BmofbUYlUUK3gIa4NCLFKxNHptQrxaq9cyeBM2ufeHLjRAjmpoU71SPs8cdBlkaTP5LOV+3/G+uNk+HrZbufd3oo9ppwL9HPnBqQB66JtvmHFSvE6ptyyEk59KDskpSE/lMyp3pXGSsCVySeHkRlsrM5bIFTTTzKo9xp1BM49cUfO55AqUqjUJg7oyujDDcRAhqfOz6O7qiIjVU1Alb9mFCM4y2SpdEEWgivTyvIpWyeQq8ni8WtlIoqyRbzypqjmjcviMe8J5knDK7iCxzUHmFl14fI9FSvYgM55lGS2DXEq90+Kzx0l8egrbxdBkqIxPKBcK5qlVoG350YCZHEivpgJFy85LVepE645JNuvYxVjWvDE1JJyLtqJR6RF4b8hj1mpHGOMfr7bXz58ppakP7jJpPYvHYTVL6EOyO/HnKtM0spAuk8cIvDGXWaL+eED3aoWRhXSZKEbgjbnMElVGIX5A8Z1SutrALpPWcngzRrj++BjlsnaHDdHVZ9uP8tk2Sw+l9sscB9EeZk1v2kAT/Hpi3U2vHz0+s/LU2tjO6FRlByxdWCK6mcICxxiV0hrWBq9dCfu7Q7LdXuXBdntMEdTJ/YlVm4R4E6WeihTJgLeFSLLwFGO/WxOh0VueM6RIJseVe8Tpx0mByof1Vj7KnoTgrF7OCZpRoHi03oezqMMEpB1QseXCHtQb48uuELtWM6PQH+7R+LxL/By72p7r5CWkvvI6QhcatQ8Ja9CpDoXMLSkNdqiGwwF/K2kXn3CVZdXR9ibwAVWV31xn9oNq3ltM7TeNYFmyuoS01pziewucsnyexbHLazOdRnV7iuKj8F47W2gk11lDOXjJbrl1s4jFc5xNQs3y5iM6p+hlcm1Ll1GMdjZXSuyM3dNbVo/OMSIdlDGv73o1ZR7faV7O6Wbm4Ssy8dXhk8EqQcoq5If7qaPHuV12lT+NA10+pvjeMq2sRPOiAeecqlqIDl48Tucs7pmMByQ3lethaZyhsHkAytKpYb/W1xq2cZjDZZHcfiCGJ40JGS9HZf/sjQNxy0xygSRsipmvLtcCuUxygeET+RwFrMEJd65FLrLJhcbbAOWu9U1J5LJy9FCsWAyX6RSk4iLKQmJ9Et+5Tj6Xnsi1bCqklEsun9LAtcYJh0LLGAQ4JwU6KivnTSOXSiiRJalCwZ31iYjFHmXGAHrrctZl2Sw0z9PQODSbUyj1OHShNMR7qz2fJU08DpN+2pU0LpNJP+3QdnMm037alchFNs1+2pW+KYlxP+1K4DKdWT/tTCefy6qfXkOriV2HfagrjRMOo37aWdPIpZJLbBoB0to7kzamUBw6uDMXj0MqKo4dKxoRSOQcUG51sG9ZR4sstYczBR20ioTmml20i2LC5VDQnEhnBOy0EPPPwXIEWZ+yE2lZOF7HkQHgXkAkZMHLgHxOsDuobJ+p+EFskeAPI8wT3nK1DhLl3PpLlxxTsaInsZT0aCLPlhxrtmml7WNVZHFMX2dew7IskV4cd7bVUmJ4wpHjv5hXjYKqiJmb0xg92V0rFKa8q1dzPrATLArlYrlMHDMy3lmhNMyKgJhYr+khHYxkOWJXbR5ZKLgUEThviKxzkVK8e3FERfiACizYvchIELudCwZhu8DUKvUYWre4NIKWdGgsbNMe2HqmFMmZUkAveI1YLNqTSRraBmSKrmJVy7GTSAlv0GRX6Cdn4ya/VseIsOaoqJ5ExT7Z4bCKpwe/ecc9iyfxMISYmjTiacXOJFkUSXbWaaDeayR6jQpvRiTcyK2OBUZhlNqsV0sljUiEctrTnS7VDDmUxNje/FZWtHjpeyyrRO4VDTjE5wrj6JBaPnUuVTMiEcrZpX5ysmktpVp6BrEQMu548Yw0axUuUquHFOSK5lRiacSYJ2unbnJZYxoVSUkWrqCoYVEU5BfoYR1RLZOGMJLp96iMrK7maCocUQqlBlF+JPOxhwLZeCyV93djGrEkW0+SCr0v36mkaDTgU1K3onhsOgJXaMaWGYVCcZB3gX1k9YSQVCKPS0Gc+yo65RGLomP+/MnPs9hphk55hKLiJKts1kKlajoCoYyERC9tfP9JdfQMMiGuG84BhVhKXtq74JWrGbFIBbEr7a71dCRSOXR+Y7Xqp6SnZ5EKqgoUOG1yRiTi+QoKLZ/Nkk9XegqxlLtVurIJjUyS64o+oJBIeSgiq3s6ClI6CqU57jrZxSMTe6UgMUj/7x9xnGMrh6FScRwq8cn8Mq7fGV9DHJdMKi+II8cLBmMWqaAksnJ6qySn5ZCKIRGvb1YZNfLZFAXe4SfnRWvMJG0wguIpr7I24x2vjs3IFObCTpd9OwblSblzNR2NYtatk2cagnxERlwrlaSWSrmYOy9SXDJVeWFB2pO6BNCOwU8zejymimyelNJRLORXTUQZZ1Xj3y5Zr03hsCoLrrKCRFtLaM+mKhAHTtudOZOqsP0+tHlwVkdZS6Uq7Wj3Fq6OtKPKq7iD8Alaqz43TKrCcnS3Vi1oqVSlkRH9SsoaJuXGY7V2Q26v4IjpeeCm97E96Csfr/DptIYJjmeoEyrNYcI64noyZXmOdyE5VDrSVlj4XGY0HGqtJJbDaj82PIv0Mb/OSGYduQ2T1khmHWUtldZIZh1pLZWqtDUWXBbolCW63SGbM+mMAtcR1jBpjQLXUdZSKY8CURpmifOt/2VGneHqSgIV9kXHo8h1dPGelFJfM1hJ45xVd81gJaE9m4lLpSA+hTwXeQqndmc2QFa3rxYT3YjsPqPFh19GYorIST2bqWl4ZHLK9HoVOQ2Pghxnm5M8TYvblNxznmuo6plkkth5vVUkdUwySacoDplHtVVkjdgk0gLyVxyvU/eGXDJZwSo52NDIxBwR+W97tYqiAZeSrDyLbS4aawpr2aTSMMSVeQ1xWHB9fi7P2aLQTNjiitBUkqNJxEzQwhRiflI4R9XldvO4iqgRm1QacweEwt9PZeXH+ICCp3ZrcxWtQnoT8fuCzEscnbtUkj8UoJUAOrBlkWug9RPAEaCdgPJEV8FwddZEcERoJaQsncyjxcIbUi2hj8+vflpfacuqJnXduqhc8Qb3GtdRNyaUCawKPyx26/T3Ay6JLHY+bw1NHZFU0CrT7oXHzqZijquMsxsaiRgcuFm5n6ppeeRy1mkHOiKpoN9drejOJf2+tKI7v+OzjiDuJhD/bs8qgnoqmShXdzVmkpbua0wEHdaZXB+UJtfHu9DG05uympZHJofMj1brxkZkEmFxskq30dBIxDShV5zhzxllEp2cSJnJ4h5GmUl5vo6W5ypicJIVT/7utN/jwkdxnK2y7rBAKxGbkglRmQV32M3W71TkhE4mjrq2vHNyO34mrKeSiMqiVcp9QyMRk+NVOpqGRibGyRW8mRbuLbyZlKC8tnmnXkNOy6QgaZVWqiNSEPTDWoJ+UBHU+s1ZQ9OAS1HWausCM0JVgcyhzpoCW0KZwCx+ur65Wqf0D7hksoroHtEnrIIAl6t0f3NGmcTWTdIa4gZcEllFRHqE8PrFKht2IzKZsHXWExYOEk3vMh7RKkccWh65nO3zFysJapjkkm5WEnSjJuf5OqOGnkkmaZ1dB7V9BnbrGQXHVXrBEZmKMLYRXJ6iap3lXx6niswsu4vWM2DHpiCtiujEbC1pPZtEWu/ccQVlIzKZsChZS1XHJJFk72pdWdOC23WOqLU2JBW3IGkwPyhWaVeHXGqyVql/Qy4lWeUqy+tDrtnhYiVn6mQMKzuU6/4gCxHhqZ9XaW7d1bvo6ESv46RoF2Onq0y9xCVmLdnNPvsdfiJ8UWH98ISB/kUJJgkpn9IsfXK7H7CYhCH5N3HslSrVO/JaJ4vGqaKUvaSSla7HZQN78on1RJOpehJV0f3qosfEeqJp6SetIV1kcDwK4Aifk6uJr88mriS2J1MV53r/bSRO9Xjt6JqpuyvEHI0zTk2paYUfq3L9NkEswCwRZ6luchFmiVm9wRMLUEsEiVg4XfEb6O241KS5P+s60KZ+prW5TLrCVstAnsZuS3clsikfKykc8SlKjP5Yra50XIrSquIUrNWl9mRq4tacHGjOAu5RfFpNW0+mNNdVeVhr/sXkkaWIiM9SP0a7UvgYU0RDMHch4pdpmkMn9b3gQvxADfVRWR9LsXQCNEyFN5DqjdV4I0LhZeU+pGXW60ubZb9BPo8+jj+MDiahKBXY/gMqohQXmf/m4yv/1/dvvdvstf8FHbw2njeHRLnI29oiYhNtAXA5D4SARy4gXc5N8CYJ9UEHUTnAAfm5wv4u9um35WaHKn0KLogCWWlgIx6GAlX+ZE9FMThUpBbQl4JJ51vcRwHpgTH7i64yFEk9nDUoXGqojZx6ynUq2Petrjd4j04xzU5SgXE8+oa9JvZ6+DYsXYcpwmc318/Qy6sN+X8Sijb+00BJcNogMgZiTwhudoct/SPZbq/yYLs9pvTxwirL4uBIqts0LpmtbOrmZFOWGxpsE4WYwXVxNof0tAnC6uX1drPdXG+2V9vt9fbqOcEl7ZMIMbzbsPcfN+yO1Mtnm2ckur99fvUT+d+L665Z/znEZVBEObXVn372hp/qlmdkTfLdz/QZwt9xUJF/X3x/cfvuw6f3716/+/Jv/u2X3968++h/+Pjmt/dvby9eXvz732ldTbJ7TKrbyz2KS/x9vcBVRenbR9Z7kj7r5b//R//1bXYqgvpb0nKcquyAU4/lfbijefz9/FtS5ilAkoWnmPRtL79e/NxIfPnhA/vyu8ckTsuXzbe/fP369eJYVflLz3t4eGhNRqznlaX3qQ60wayn/EqLR62MRSPjovrLKGSfT8Gm5t2UuDrlG5TT13x3pKCwaX9TfjeHIGCx8jAZwfzpKzMyG0nQnZeSlLKK+hNnoTb/g/7p0UCd1dsk/YmZopFGEk0R//G9rcHrzKZNr49KUtmGr5B/P/qZyMnpC++45AbZVfQfdRaNStCm/mUpbFvBgwpvSKYpBKNPzS8EpStvMSLBsgr54f40D9a4b9/TQMF+kgacxNGu9q9W+yvnJTS9T27oo+i0KeEGGLlqm/9MHzPsniMlSaE2LesptDisSoCUFBhi88WwozcplwJV/tSOS0G7Vjki9TIIA5VwOFGCO+4fF+03DBfvi0Ax4DLgHtfH4JZ+nxVB1XDd6JEbfH5an/tzk4qlUPWgdOHXPHsgZasZsS4FKhBJOkt/jhTCjCCZbeVxqmgpUBljnNNDkkN530zzfgr+kzbsbZ/5+ctbnw4bshSn9Xn9QYdKX4YmjSEZlG3icPQLyRjS6JN5EGvD2RR8EnfY9Ez66dFP81isEWpb0Pa93nGYoFXsEwEozg5zmGHdDui7LuUcBt9TiCNKw7j2Sy76ecYwLuhLKNGkGvvNTzO8WcCqQGnJjuAuR6GdSb8TJsFnPc8s0DdUl77ghK4i4v98tame637fzW2/X5g7cr6n8ybO12WN0q09+GzETodag9e+6x2a2RCI19c0+uDwLPTRcQ23P6RDNwudQlwXetvibw0dwWqeT4dVZswabNMR4MLAUMcyqpDLKhsgtkjXz1gG/9SPW/dz+tHZgKX/l8AOspi6nHTIRFcxsTC+4nvumjHb99fl0cpiTugf8ihbsJQo+mCIMI3W7kl5rz/cvrv1XtNV2nfNKn2QlFG9RRzFi3aSA5Auyjju4Hilbnzm5Du5uTGIm+QnHxXJ/Y8Gcas/2r1cWeQ3rH3xbuvF8vd0rfzXv37Ybjuo0boYDJrfeMkEQNqdCpTAYVXSQqKIFSRLLaA2EluDQPLiq4hHJ/hQUCRYcwoNAi0hHUezjJlJK7oqaB4vtZC6UBgsS/GpRIvdlC7YnjSyUFlwyIMCqnCwXgIOikzjwEx23MOZjC5wAUFFWyjbRwisjkfdvR8AsJjUcUCoxx2CaidaOLqgEaVg3VOMRaM7bTTAchvDldukhCpseQjVl+cFVBYSJDJSP6QohkIkowwog5VgfVL5VPYbKbZgkIX+BFnqITvehzCztxdOmhm+NRLJwIqgMW3GYPVqmVdWxEynvAGTzNmkYENhEqxdllVxRh8+J1PlyBuuXfcbl7LUTUDobiFzFhZkodTMnLjdTqOm+HFcC156fK2U1ychxOD1RmsMfR0Fps5eVeYKo8jD3erJR1lCusUqtgAhXBdailNlSSRtp8dx+pP46nFw41VfPcaBhlBckxjHLOOo1DQDfSvrJK1yTZxmvacxt1oWNXFqaXpRSJeF4li1LHSHczo7BgEpUbg5DqqYxBlKvXFrF5tUkIN6ZvYgjSEaCRIz4CQs7oe5i1UaxDoWPS3B4tB/GERp9wlNoh5wigt5TeRFPSLp5H8hmr+PmzfFdCPTPUyNeHG0o/9jUV9/uLlhC5VIOTotAZOjLDR//XpLWK1IjIH6xBtEZomXxqNpZgUwUWyZR1GUlukmMaQN2Ch8cIxyvQjyYfg0/OD2m3o0pe5lEqVQqOKTCOpVbhAx3ElHw6PwCstp4/BKY3dOFBNLKy2ETWLIl7tGERRWe8bhFdZ0RhFUFlvGEdQWK0ZxFOb+0/Am+aEwnR+FL1CyP6V60grNAqkyjR9FKPVqosLcfhxeaQY/jVJh6eiTE8WohdAvXfpVXnFYPIqjMpHvI9BDADpNPu0bu15LqWtsYlAGrfC0qdeJQFtsnfBYU1DTYutEqdtdvRiLm9H8CLTd1QpP212dCKzd1YqARYcP+HFou6sTnjagOuELzbxmjaFOhFKvrDYtlU4UfaPql1fWdEgiFIjeUGOHaGnM/tDmjn1X4BijEnefm5N/o213lUmBJk19pM9nF2AeD3STjcyGm0CaVHS47DEgr4V7rH+lv/hljoNoL+8rpqj1RJV+No/Z3oZg638+ne9KxxECsD1G1amwgkj20u5WELu7QqsRP49Phyj12rPxw3PymiVXhGSkKUeXpLQ3XXbZFZ7t/DD7qbg3TfiEpD4a336sy7+ZHVSAoRTT9Ne57wDYClN0oUB24cDM7laMtmmsotmNCOtU8DA1dRZZlQVZ7O1iXH9L/mGKEWGMf7zaXj9/Vv/YfzZFLKMQP6D4rv6p/WSK9pDsTmX9PfunKc4fD+i+sRb7pwynxKS2RNXT6GID+ba7SN6umHffwCP69Pg8XZJXmOMYoE9fFoWG794HhQZ2pVjxNIgB8uBFJWDko8LCtQEs2wdMUUydHLkwyNx3kgMCdvuncd8KDM/OiNDhoQNspXGfAa7K0E0RNhriqg6UTbDbcmiN3e4i9s21pCPXRxw11/DoTXsKD9w2TvDIR4WNJQPYSePhhqBrPODh+8YDHltlpqcIO6qIWQlWCWe4/g4VOMGVMUPcn5v32ZJH8dT5fWrvklAvciQwnQu5YGG/UE8EZBDhFN+mdxAxlI8qFzXMgHfxXdN8Ke5qmtGERx/Fpr29DFu+vWYGjMnXaise5vikPTvg1J1x2CuvDuHpep4j81iMn2XID77CDp0ZdoIqR6oTnASJ9DyEObbxJEiCPfZhCo9fGE8jJMAVLDLtYnfo2fX1xPcIJPaNO+hnOG/BzQYxiuDgym+unenuoWFV19/Si3jdLAtWO4fARQr6URGs/ByFofnqwRJqM86ClToaYznFBjdGM2gD1zwYVznBHoypHOC34ylwaIspuQCVjUfgUeuxiBNc4/UOAe5gDAKOXRivRAhAKxeoBT6Yj8Fab0vlKadXgL3O5VjviIk+4Unm8zYLx0o8WZJGOb3Lkko3Ek1oqN8nJ0mhq6ikhyHNB5xuihkECTxmggJw0IMDofSlTxeg2+cvXMA+v97Cw3ZfQ8P2zjddIPfe3gGRIxei+yEtbVVtRoliZFJBQJE7F3mucEkr4QS4HmeRP80HLzz4QU0Bhh0UOljkCAK6PWzR4PTQ4++N64sivs/OgNhUnyWiFrjZvUjo0GANDmODkTytH1epe9uuBYDHps9rsHVaSMDuFEJVnMoKh6qXknU4qM1d81CO3vjN80tWC39CAuajNEcFdZRKL8bYbXopU9ntTHFo+q9st43E4JYHGLjwJW5vp/ghznEa4jRQ8GagQjHuzCGaojF2801UlT67AAwGu1QJnBAMS2ZDhjAKVyOzXIvTpbNa19ElAzmAYUbrorhLaG1Gn7pctkdDuIzzdtQNuMopb11o6AZiqV2WUjAHvd7AgXk7x+T4NJc28kpgKr4bFaEUrl8rIql4wFOEUnL1pIwFJiu9l99e4kE1XefseY1SeuNEEY0+wgEGxp7qAEOrsxIKC1IZy01FqCQ/dStduXKFobHaWX8uvUfZxhrdVumWq4ZfqvLLkeqHcWzwIghp7dhyhGRkLh5Sk0g4POoaRb0Y8gAnVqP7Q/do0Un/DLJ/ZKX36NR+Y4wR2YF0/ps6DEX7iDCYqZWuzCuj5UUGCady4VkZzM5u0QROORPZnequJNWOHVRuyQkBiJ0DXNJNObU9rBFU79mr06JqFR7ARMsCVH95rn3qgPqtK+mzBptH8k/VWLtDc1c3rn06tZ/1LlnzcNmLgF4cd278q6AqYubkKUZPy9VWiNWqHD48Rv37s5PRdopbF3p5XvvyE140WYy+OxDj68eqfPNobLLQPc1oAhLHkqNZosgsb6zji6qwKLZwtU4UUeJ0ZSlqxIweBKTp8qn3P8OE1zALL/DpoTS+F0K817ZDG5/7dJ8eSviUoiQK2Dsw4c4GqUEQXEAQRo+3AZKdjxQC5OihAMqaHBdRFhKrEDgoHABZ5VMaaMeftbzHjJR+yza39b05anMFw9VFhHE7ohl7qU4bwcxyyARlXidNUPh10gRpVKlMABYqlREUp1LZ4gDIGlYqfnzzt+fhwPjVnYFVx6gIqdvm6qk9WdAd8G8/L1+tUocooqUrSOoYZXoNgfFQRIvzWGWgHWnxXiy5mVBHiQ7LPpXVUU5RHIp8VisjBSjBcWyfVfQwjS3EEZH/tlcwOHkWL42RNZCwbMirjiU6kK6OQnd3bDHYNOJyu3m0R6ofAg1/P5HeNMYHFDyJT83YQe+LLKG7JLDgdNuFIdcs8ODlifRB1Mm8C4KyXJq8GgI+Pr/6CQgRJqvIgI8e14gS6yY8qAo/LBZ9ASvjiBaoNUCs+9jwaN3ostOE9hj2GY2D33N0Z53FOFi6DaoOIfR+ow4jOF6mDHKw71aPd+HSDFsdgx58h6g5cWJd6Lkv2pujhfYIz60h6mH87rTf03M/ECP4lHQ3ZRbc4cra4CmdKt892MJkkbWp80V/0OoQS67dNBCC8nrJIaEWinW5oSA/WIM0uxVQOCA9dQcmWJxXByNTgeubK3tz1xuibAmptK5WdGQIkboiItUivH5hPW8q7Dtxeu8IAGP7/AUAytJbMDoYz+1rOsAAvaQnxQRPXeoBsYloeYoq+wEow8uyuwhEWRXR/soWqToWGAluwqsDRQkAinj/SRkGYlZGMcj03Lo4NjjWOVXjlMaDZHofwn4ljKLYrVn0CO0cmjo493GKdjE2HvTMUZtZNT1XnKNI7HnRHL58SrP0yXycPgCmmVNFaX3KtbRpcDigSj45TYClvnl0QAPRezJ6QDbTnQGQyhUVI7y0wo9VCZvZU3DwTJ8SgGY+QSyMx1QDHLt1wwGQ7Vh/AFXixnYQWNEfIPYuq+IUQFQ2qJZVeJl7Eah1UIHi6JAKbj1KAeotK5k7IzkM27PyBc+1qUIkmXZ3OEfwC6S9GMFHIZa5R2W06F5dDpf6ycnYrs32kk373kGJrm8pxvYfCrTkvkYLwjQNRj1SH3u4UWCaiiGIHyW5ed6OkSxrIA7y/tbvsqcMRRy7Mt8sj/t5FhunJ04y/XXJNnISmmwsDWLbFNIkLw2HTkMEo72BIQCd4up3vUMEMjJZfPlbCpCjUPCUrDz6nXWNIBA22ZjfGZ0J6aK34yjDdma8vGkKInOBoYEgumysDWNq1B7GrjubAwEoiqPlS7xaQBajqAmMZUM0QGtmQbRG0aMK8Ih+mrHX2hdvt8Fg2+um+8f2Cg12oTko+/2ipx9tGHs1giv72jD2amxHMUMo86HIAGX52r0uir0WdpDCXozJeQwOTIHSMEusRtNDtHLpAVNdFHsti++EaoIAKImzSu5swgYRQGPjpQhAm9DfkRKS7cCLBrIexBbMbW7lH3Fs0+2yXbh6fGKBwA61QUhJosV315Xik8/XN9YNfI8keBNMitJvJtZlJUpIufPod2x94HC1ydMD95frxV+23S8JitqLn/XPmyRkn4h2epnDby6Q9i4C6KSh82LzHxSCPZX79eLl14uf8yL7HQfVyw8f2JffPSZxWr5svv3l69evF8eqyl963sPDw6a+RrAhQ0hiKu9THWiD6biShvyu2Q1h0ariVH8ZhezzKdjUvJsSV6d803kxuWUfb7PX/hd02ByCgMXKw2QE86evX9PvvvuZrZey1z6/y+lbVEVNtvkf9E+PBvrZmyTpT8w6jTSSaIr4j+//Ts2XZPeYGO/lHsUl7gO9fWSLsiX55d//o//6NjsVQf/tN2HFEO/RKaY2JDEO5X+Z0cyMr9mkqMH4lJXVr3SL+L+saWbN/+R2/HrRvjW+CYr+3lbxLbWep6CNv7Jt/+Pi+4vbdx8+vX/3+t2Xf/Nvv/z25t1H/9ObD7cXLy9+/jMxwNev3zXnV375enG9ufp6Qb7BaZDRLpF89duXv1z++PXiz4STkDacJEiKEvzLPKUop1c3d9XrOhuGyaXAJD4Ze1RPtwH5m0Rv8S4YPAlA/vt5n8UhLnqOJn9HgdqgEcnbLiDrUMPdpubqMqg2Lv2KoFDn5jjsvvRUMY9mmD97dWqGXzW7iJ9QdSQfT0VEYpbVKYyyl22mel2aa7Aut9mn71zk3CmAzLO6GnKzbBJyV9GwnJDL2dGOmYIKb6gh+NlAvqQeKtg3rFXh5TaXhJ4QiREhyCrkh/uTExKWktpMp8bhfmsKF0wDm9FrsrZJ4pRrLjedLNRH3/vdTwvWGfgsbd3d2VXYHNBQD6d+M1B0gT9aYXZhpJkbthV4mF87NzQjBzUu8DNE5qaN85s10jB3EQJGhfLcRyWpIE5K7thxlRuCsX80R7lR+dMeZpWq+OiqJhYoiuvlMpI3rspVMwyJsKvGva8kXN8srvKFOtF0ni2jUl07hnWesOMqBQ65oNhVzcrvntbR5tFUyATscX0wwIV4nND3B9nucb3g6yYPmnVUx+hNgbIjMZ2EtZMYzyyi147nV5zDfcEJPXmCV555D5tP0On3CNhwDr4IzEZe7VC7dTcFyUC9YUUBm9yxA8egKfj85a3/ul2WL6GN0y34+0Q/irMDNAHHSzmw9fE9lX9EaRjXB4TcgcMqjyaNq9/UQ+A0zGiY+392aM0N4cyfsRvjsRmuW8NRiv7qkzMq1qkV9LtNHP7/fQFSsMVo3IGxjVl59zXb7f06H1B0lqJRX3rHLMFeGqWZ9wEVEcmBzH/z8ZX/6/u3XqPcW9hJlub6bIfZiZprbTVbh2q2czW8kjvN38luv8p6c3swV7DiPInxhvVUi+EXYt3WHv3eo10piboA8OtfP2y3SlGXFLBNMg0EfnNX+7LeHZLttmmqxy0GsX7vD7u2lTdIvMfS4dVivCna0hK2qrgKFaSxAFM3hVOXt7ggrpxd7+pW2Ta/mParPNhujylqeiMTkzRyvBmeZZYxPL9xPwmhrcUC0bU7FSgBU9ahQWmrAkhtNRqItqB+zwdEWYMFo6t92wpO3RARRGP7rBKIvBYMRhnhbPwuwIjr8WD0JYhglkERkSwp4GTOYGHU5vV1OhiNDRiIMgxYezFg7cWnEtVOSGCkdXAg6vZl81wYiLgODUTbIQ8KuEalQwPSFsGZrQUDU+bTR6hB5XWIIBqPe8hS16EBaXuElPYIpyzawtWGBgtGFwLs+1swGGWdOzIYbR0ciLqY9NFg2lowMGWPOwQ3GhkCgiqkWx9RCjgR4wHDKMbd83AwQns8GH2gbXIM2ibHkG1yDNkmJyVc09dggejKQ7gVgAYLRlcBV1UbLChd9TPRMai+ISaITvZmIpTAFgxEWQk4/yoB51/lU9kffgGQ1sGBqIPtE2B7hBNsl3CC7RNgp9Wws+qHMIMrcS2YpTKcNMcVAISNsGy3P4a7KfbSpnBOdj+UgkoCyX6e30ahFwZ1d/CiNFDcuZud+6myJFLoa5oHW6PmvdIulorhOUdSmmendDjbOGaMB7rzOnB/rMM8jWumoD5trm3pLpYZa++VR4e1j2XGWtIXDXVJu0iGnBWqTgrDuglpF0vMqtYWTOtlWRjXyzrfpfvETWraNy27WIY2JMMeFMelLu8wnk2J0aVtI7nIuyrL4uCIIlljbJn1Swap76IpW6RT29qmj6+UIRq9omnnI06pX+CDTtvcJ7ipyTMYjTHBkvUtxdiqoM/b5gVuDsGZq5njgJUJ4OHPLsuq+lVe3SHQ+OKNSas7RpDXvF6rN47qzZFcNFAoj0ySOboxopnKyJvFNmjux3dWBp6YzJUMUQwUDU+/DzJOWuEmkpZhDK3EXLMGmUrd51hnFNs2n4wUjGJbl5QcFaXKMoqwoPQgYCXXTtAAxVBRgel7nmrHXzhSxtGtWird5v71h9t3t7ot/Wvq18RoTKZ/bnFi7SApo/pRiShWKYksfR4V3K1czCGMRwg1lPKkdlGM5tSWq6X6o322wkjIOLqlRQ4qi+eL1jjorpZPNTBnuMnNjZmGYWxjDUl+8lGR3P9opGEU+1sdKZY4IKmqnnRbj+GFMcOZXdyfrPQb33w2h9/1Zorc/N6hZ9fPcN65lJJlems8b2gNj5cwNp2cw9uun6NnN9cO1Y7ALbXWJPSgZedhE1oxnwJEN71gXT8g40b0CN92j+CRHZCHFtrD2uvbxXcDf/DQMsfo9mrDo49i+Ao2QrZXiQk84b93k/VjdBi1d/jpgFNXtp0zQKgOmXtfR4IH4PZaW9/u0DJbXHuFCaqcKGxxARTiJEhyJxo7ZBiVucIat5nKXHn1W6xy8AqfA6VjdHu1Reqkjjew9voqRwIrGIV0qHs98eICO5AeoQOovXEp9gZW62AS4ULtGB5yjuJA7Qgcfo4CrZhPYak7R2H7ODao2AEu6JgfWucM3VptgQ8K+xbaMlvYNW+ZRzC3zNulVvoALkkl9VQNaqCoW7nj8oDN4kO8d6N7ygC87uBWc8cBs/bgQmwPDdkWKZ/sMlPMJQJbkXAkukcHUKpya8tQJsgdrvHahiOpYwbw1ROHqscskCsozkQPCAD00s1/d+WiQwda73Gks8UGUPngK10wMdTZoQOtTjnS2WKDrVC50tmhg61SOVSaa54UXFI6WEtypHbMALNa5UhqATX/qxyKrLRVQt9faVM93+RuXW6Wp5y6hbDZ4l58Y0UvLwZ+QIk9cYyb10jMM2eSxtYdsojJtkANoLMkjXJ6/CpVODVjk4YJEUASqFtR93nAY1lzCQLgaEafQItV76mJ2jP+PTDIpJ02UnY78DyhM2xLrZ0r4CABVjpBhtLZvMbsQmgDDaS0noKQP212N0V6xwRgZfYAXhJm2NZNpt+/ZgTfEIyxgZp3R2Kn4CsvKQO253BdXntrqAe2zEPS0tLHnIElDlBt626QONA3QLXVRxpWFwIHsLa19IiuHSgcwtor3D5/4UbjANhe5fPrrRuVA2BLlQcn9eUAVl/GfRB4wzjGhu3foMVOwWEse4/ik9WyjsCyPfa3uAxBFYZFdC+9EioGgpjJ1VlreYKpT89oQAR0fqmFqxmGTwUBap2Aw0puthtdie7hAWSXuL085Yc4x2mI00Dp7rCOeAEJ2AyqfugmoetDYNqX0AHs3kM3uQpfJxcpQOWzd4xyVNAXmhoey+PPwqQI6Fwny/rWhG7C4C5SyJgQRuGKCWvpXCfLbtlKN1UwK1lSmjv8RFpR8u96PXm99M2J10iqi3bdgNh1Upn/zepUKHiRAEvliBNmkB9VpU8fVYdMxQz4219vmz6DVSJtEK6V24PLJDdPZYVDdQcOKuamEyry0ROx6BaTxdqwTlJkTCDJYUeJYHV3kNrVUrfEL2bQfMYBlsJFeNh52B6z1s1mzUEsfEjgcC4GKl9A4mIuBqZ9Cd3ZXAzU6osUzsYV+1Ma2F4VECZkkcxZkmxP4ysnx+BI/lqribh90ffsS4l+r8V4tNchdP4wR5j2Y9Iezz9VkbnfC4HQDhhUreVig0gv4LLCEJbwFpnFXWiR5AE2qGarlSqRYLA1qSEo0MxfpNvBHH8Kz14ijywWO2X6hwSg6u3n6CLpwLPxATKqKky9RLsqNBN8mJFwC56VFleBp6q5yPB6/R0ZRyS4cql8zPHtL4kIRg/2NmpdoY8wQeuQ8vNd+loBX/Aa49qNl0WKwe6szgdSLuS2wLA13Xp5YSp5ER3Uyt1yGOkr3ZSOGQOs3a0dRAjtDugbYjLsPuLgztYbh8jsUwJY9Q51O1Js5/BCqBjM2wV3luNC8gAbfgblQjDUvVfR9MaF7jmFuxmUK/1DAkczKBfSR+jOZlAulE/wv71lx5i+BlBlQdbeBj378mM0VeQXiOSF3eWvCWR/+k5ABTC4aeGADjssJGKBBWLPbcxos0SvlgFAg0qeReC1L7Ccr5KD+zEv6FuHum7M64cZ2RFcMy/mtq82DQT4QZwFd0qzIZZWbxC3bc75cMYO8CeIYaDydr2ivBYMShxWeVJXURvWfVJXLO2o9CK3oraj9ovcYnGK79YqqjN4tlYmD9B2+q+Zi8Wl9yqPfiqKa8HAnopYaLJsn9SbVmK/3KoMFOY2aBbxF/AA2wVIhT0cZOsAqXCAB9tGQAns0CDbCEgLxvAWZJUbSl8LBtZSmL2cl+SnMz3qmZ/UbUkCd44+6niuG1jrlzxzjZEMTV577z1XHrU4LBV59sDuIagfEAIvHyMJ6iVlFK079z3FsmkRRmCkSu9OSicQVOX1iHAijyjWaloVVPaQFjKjCWjOVjuV1vSWhQpAv/VGY1xODa3Q3maeYkGXeUB5PSJcYbLTxwE7c5NcPpUVTs7TFtfcyjeoa7PWkQbPog8hbApjA5UXWYBL6pRO9TySQNcc7FtvK4YGVS7qTdrbfYMxBHye2Omag527CsYY51WUnGtI1PNrlPYuTlfiRyhWmd4hseFAUQUa0yORsBEcoEJSoggqoMYeEFDl7gQrssMD1AhYCsd4VgOAMahG8zOVx4P65juEvl6bJLxte0coQLlhIWgKs1YXoLt3hZOwuNfduarvK55h0woHWagwzWKJ8mqVLD+6eGfuiekF7jOYjdLSQ7bopOJ/rLYejcNsN41sXLfY7XUTdmtW/4BTXKhsl/DSPohsp0Kpbecp0GjJhez+PlY6rbagoY9up4TuDZuJaGN+09tUwwrTXO324yi9Uxl4DBJNe3QxFFR5MFI1ig5QHoxEtDFdl4c42pmXBxKZiX394YY0JmRygDSSSiJ7PIBvdzwht5VxdZuOBhLVOQdTxYrNMI6SDWeUQaKwATQibGIY0mUq1+3GfJn6Hbo5YbhT2BcY8TUxzOiwtjmxjTnxqUSFwmrgmLGLZEZ6yINCt5R2cUwpI4VN8wljpLwzPieMtropbGIY0qFQm6+JYkYY0yff9AjbKIaEWHGxYsyJtZYk5rRJqWvXJoYZXV4oHFce0TUxzOgK7damsGlt1JYWx3way4dzwlK3rygteop6vVuXsItkRmpSKSyrhEmXYdljPISZbi/cRhETmq1bqK4+LA3QFCZ7NCVsqWYQx3DEdIwUHqUbMbZRzEeEmnzqZ3y5dOzcPVJayxmzDiIakNNlTf30jmOZpRmVJS5009tHMiPdnRQOxE9KrvKZd95IX83J3DhPtVzHcXoolFDfVZqsg1hmtI0HNk3aQSyLyZSugdWv0/EJdVYfJ8S6a4/82ZwebxPDfDanR6dx3WFxNqfJ2EWyITVrgmdxbSaUetRdHIsJpS5jpHzjgT+h1ONrYlhMKDX5kPotooUJpR5hrPHs+PKEUpMT6+1hcieUepRNDGM6s6o5jmg+m9VjzdWf4ObPZjU7bpvWlk1NNfmaKMazWT260qKrLrWNWdoYk8yDlR4jHzN2kaxm7NqkTSQbUsNR0DyyzbKBHrdlw2cyNrEcmrA1AD3GNorVsoHuLhG7Ea67S1SgKPZVd+LmV0Pi0yFSO7OygLCn+VNFMYDvtxZKvsTDLOW1SffqVHhtfG+CZe/zo0OTliINZa4u+y9lNboMsrSZLJb2rxfgfXGzfTxstzBvGBDLMKtR0/g58oNTca/iRI1v8HFivU6rt0yjXUpAXOpTCb1Qnwk1Lf+TRC9BW1YHLixMNi1BAyim2Vz7JwRXzIMGUuxGrJFO+wZoUO9G14WUXX0otx4zeNMaJcL0FDjtex4hg2GxsErV+QpNFcGWkioCKBZV5PFQQTOeQNrnNE+oq7y0OVSmcYqaazqaQm1zNYei27jGB/cYYLJXmEsuC2jj24mod3l89mCQT8956w+lhpr4cHYSFf0QC1SZPMjBEaLusVegRdcxr00daV2K2czbdrHMNZea8QiOfuvU6PdIZG+IsmbPEmGMf7zaXj9/BmKHHs7cHD2Gx8Fc0zgPye5kMkec24UhmZuERffGSGsa4o8HdA9TURiSuSFYdG+MtKYhyijEDyi+A7FFC2ZujhbBm+F9eyOaY5TbtNRssga3XvMIs17D7E6T5pc5DqK9yhr2tPskseulmW6B5tHj4zpfnFmpLKBTlR2w1YIrsRyzUYFjjErrtqmFq92t+7tDst1e5cF2e0yR2r2MSa42SfQmOj0VIstpU0uRZOEpxn636kfhWx3g6ZGR/edz6Lr8w6w458stm9nMbhZLeW+BJ66Zt5jPJnuMxdaNBGknAmyJv4/ijWPbXNi30zEDcD1BoWzqrjUWLS8+1cxLcH3ZfBTX2Ow9io7JpwosM76Mkpy0LqY6OAjf6h25XXzCVZZVxzXv3R9QVfmNuwI/qHR603leTcGEJbdLbptz09jeAqJNaZrhiUqUmcIVWpcpp49CmbMGPbNQQLvMowg887TIkJnIMK0yUqjWrgGL3Mldhga1bhnFaLd8HcvOwD34qpWmc11LB7zsfRG4+jPHtsjtOdjMjHw+9/59fDJhILxZhfxwr+Z2d8l+u8qf4umVt2lsbxnUpm7wILXyVlXntzBMUZ8FSZfj4cY6hj4B6glAnKGwefZQ6EC2X51vs69x88XFMLwxRbKdNIpkPhKV/WNv2pKWccxlEYwUMy+FdrK4OOaywifyOQpY4xfu7KQtYpnLi7cByu1UTSHMxeTooQArXstgFgJxEWUhyQGCa6mOjwQjDcZ+QkBzoeVTGtgpmyBYtGRBgHNSgKOysmzKuEBGwlgCKxTcSU5ALbb2s/jf0B3qWWe0vPkwT1/jHHEOYNVn0EXtEO8Fe51LSngIkL2qmSAuDmSvamynOQ50r2ombRELqFc1UzWFAO9VzWQtg8H2qobq+EhOelV7hZA2HPaJZsomCKC9qmFTxgUyF9ZUcNJWGwoaA1h276am4SEYS4ljKx2j6IYiDigXHJRdZm/jGafdkLeLaEPcXM6NdlEcVYI3wiUy5jAQY06LIqlz1pwrQ3K6VKRA61gpl1zqyENEr+zPw2zEvTvYbJjZ+vxs2XUPZ8wN1iK1zkDlyGstKS4anhVtQ7tbHfbVy7XFvGttT9vqqsjimIw5APKRmcWL4y4ntXhWPTOs5W+ca0dWx4OqiJnL4hg9iS5gC63VtRhztG/2zJFl+RSVyWNGRnfWpXFWBMWwLhpo0h0bLonsqs0ji62aWhLYG8Zzc91dfSfliIrwARXLxzDmjWpGoqy3i8LoxAtqbRo8FrZbTBtFNBxYMIymTRT7shWJmAJ8W8t6I42LLeMkfW1TOI1rY2fhCFbErzZ0dV+ZhCcnZ6GrY0S056ionnSrU7LDYRWrXRfhH2cuZJyCDCPZTbrEtGIn3BYrBDsXN0ij14j2Gn5vBmO8UV4dC4zCKF3eA5CKGUEYC2lPNJvrGCJYyxD79lDWYuDWYyqoRLZaBgjm50vj6JAmOF1uZaQ6RhDGQnapn5yW21qpij6+uQQynnrxjDSdFS5SwYMwci1zIHNRxLgniXtMuaAxiK2YJAuttTQYAFL8Aj1AyGlxgCSR7L9HZSS4bqepbQRoLDKI8iOZyT4UaNkTs7yfGoOYixH71VXoL3Vc7C5IGHS5Pj2mbiOHhwUlzbpZWsYzloiDvAPykeAJM6k4HpKlLNvqN0Uxl0PnAvmTn2exRfZNUYzlxElWLa9KS3V00Y0FJAS6XPawKlXQx7eRYNcEDgDMReSlzLW4XMcIw0oKc6xhp6SDsBJC5x2CFUklJT2GlZSqQIFFEzKCMJ8roFD4MJ98qtADmIu4A+iCJiA2Yuyq7wDAQsRDEQnuLymI6ACs55EQmcODMvdqQ9BIP+4fcZxjgfNlqSwOkPn9gTL2Q7w7HexlcaGshAVxZDURH2NYSUkigWtwJSEtgpUMAnp9AzCS42MBSLvDT5ZFaIxj1QwExVNeZW0RsFpXmkFZzjctlkS7+CBTXksdHQhARkHkEJAUH5HREkiJaYFACrJl0eFCQQgLC9KC1GWBNvx+mtEDQ1W0/KCcjlYhOoT8Ms6qxp9mAtVScDBBpFZZQSBhJPZYENJwYNGazHEgJO334fKT0TqaWiAIUUfRO9Y6oo62L1oPsBIEU1cbHAhJObqDKectEIQoMvYG0dTggDQJQK2BnY2CI6ZnlpveRXzoWD624IOBdexWM8IJEGDHDiGrhwIRZrXLxgGCEmW9TLiM52BABCKTg+l27OZA9BgdatQBIbTBARt1QGhqgcBGHRCiWiAIUfYLGQtgIOJs9oTmOFCjNAhJDQ7YKA1CUwsEMkpDaZgllpvXy3hQA0kQaZb7fuMRIIQi9YftpIImc2gQdXNMyHk5iMQey73DpCA+hXoO9izOmQpsiQT3whaN18jvPiPDR6MmUorIoG7OtDQotmLK9BpATIMCIMZwi4+nyGCzjyurPl5or6nHsRXEzqkBCOpwbAWdojhk3tgARI2wLIUF5K84hqhvQyRbUQFA3jUgtlKOiPy3vQLQM0ACEZVn8fLVZk1ZLZa1MCy/eq8hDWtfwxeJM1zkmckyWOHhCzKaTszkaE8m+GLYVffL7eYRQNIIy1oYcwGEwt9PZeXH+ICCp3azEUCpENyF9H1BZjJGpw2VxA/hQeXTATIDr4mg5XPgweWXJ7oGhiuHSeBQgCajLA1m1GLZDSSozMfnVz9B62wxYYRC1kCw6ja4awehbQxnK68q/LDYQfTrAyRLUey8m72iDsZaDsAkWvsZQb6UI8AYugGxlIIDk/X4qZYWxV4MRM3vYKzl/G62gjsX9Lv+Cu6CJIMdnbkcze0cvpT6hgmAnB7IVpLZnYSZIP17CVw5B4ip8gFkqny8C5c9vylraVFsxZBZEVB3NYKylBUnAB1EA2IppUEDm63P8WwFGpwTmYnSPCKyIOQ5hJLnEFJwkhVP/u603+PCR3GcAawgLIBaSk3JJKjMgjtsso07lTgBs5VGXV7eGdzRnsnqgSwlZRFAaW9ALKXkGKBLaUBspRhcMZsp0bxltiAkKK+3EGJaHABBAK1SBwMg5wcYOT9AyGk9tNgrGiABiQKa38/goOQxFy5w8lo4W3lZ/HR9cwVR5gdItqKK6B7Rh6yCAJcA3dwcz1Zg65LHXtoAyVJUEZHeIbx+AbCpNoKylQWxLqB9HIgrpTwigEMHLYq9mO3zFyByGhx7QTcgcm5gxDyHGBn0OLaCIHYIYPYE2P1fFBwBersRFIQstolbnqIKYsmWhwghMsvuIijjdVgAwqqITsVghPVYlsJ694DWukZQtrKiBEZTh2MpSOaGXVmRskt2qSSY7UKgDUIK4wcFQCs6RIIRBVDnhkggokqA5fAhksZxYGvX5WRUa3tw1vYoCpHgwZ04ae7G1Tvm6EQv1qRoF2OL1aVe4BIuqOhmT/0OPxE9USF5ssJA/SKBi2SUT2mWPtms+i8mYAj9DRxPpTphj6bWiaaYVZSyt1iy0m68NrAlHxZWMpnOJ1EV3QNLHsPCSqa1grSQdBnCaozAkT2HhpFenzYEkdpDQUmz21sbSYM6Bju6GGp6jZejcIYILDSt8GNVQrcDYng3SXBQyeQUbpIC3MSJ4WGSQIALi5W+gdoOCUaY7anUgTK406fN5VDrDZWBOMA9le7KY1NyQPSN0IAERn8A1ZAOCUhYVZwCmM6zh4KRBjfwBx7h36P4BKSsh3Iy64V4nEr28+wZoSiOSPvtx2gnu5TKi0tiMYcgZu+mNEdZ6vvFhfnzKdRfZH0QRujaZ5hWbyDeG+vwRnDG1517FGHR0xelWPyclibOD7yvJsehUJQ2OURfesMh+W6P4hIP7ENjvPSOWYK9NEoz7wMqohQXmf/m4yv/1/dvvdvstf8FHbwWzFvmQ3kORtdgSdiOgGxHIRtd8U7wJgmBGAd4AtaABKuwv4t9+n252aGKkR0wASW/UAmkX8FcURq45dEJbP4EAkuqIn38mIw8ivsoIMMPzP6iCylFUo/gA0OiptP5hKqjfh4qYA2bn3Zg571h+r3buiV6TxuiX//6Ybv13rX+DrRwSeFtXtaoWzjy2UclMVYFAESPzxS6CeW+VGtqrUaRAYLg/VcgtOG7mpp489fgTA20I2LijLrPt0fwZk86qqO8/nD77tZ7TftSs4LcIZU4IL+SsSHbmU3yLMVpxT6wcSEKAr91TBKtxsQegDRlYQ2X1zVcUWWT4TgJi3uLetHj0JdLLQAKRL4jf0b0Kdkd+f50iFJvj+tjbQatT1+3mtSN2v2gMmkapZg+Cu/Bced9FAQFXd6OEcHNKuSH+xN4sW+vKZSnPM+KqrnCuRINaWNxiXV7LX02/RIvm7RCwXUPW9q1M0l+sm9f0vvkxgalFZNnD7joplVWgAv5Sw9f1ktSgI1Z++A9TMvYDx6Mu6olyAhj/OPV9vr5M2jkh2R3KqFB/3hA91A2CI5R7rF3tr32te1HaL1lFOIHFN/B9pE5uiRtXnNECMzGPOzOMltYFvaZNmT+qIKzwY0zpsp4cLrQeGCHDVOPrT901FmqspxYkQFGHBxRZDWUbBv78qmscAKCFGOcs9mnmz6jqd/NQJ+TRQkKiuwN3tMCTYdv3XIEm6tffXq93f7z316pRrp977/69Mn/9Pnjp7efv7x7e6vM9vHjl/cfX715+5kC1P9i6xpscZwEuFZF+udXn9/866vPb/1fP5J/+W/e/uXVb++/+J//4v/66m9v/O2zqytDqNvfPn36+PnLrX/dotkCmYgiJq5R/vbqw9uRif6v//eUVf/r189vnt1cP3tVf9JG/fz2Xzigr6622nivP3749PFvb//2xX/96sur9x//SorF21vyWRXjw69v33x5f0uA/vaXd3/1//Lu/SS9cfW/BuPe9nDEn3TxP92+8l9//rdPXz4KqUbOyjWpiDk+v3r33n//7lf/AymO70gN+fLx9cf3bVkYsemUBQb72xfyx6dXrfx/fjurPo2tBp0MMknFO8L35t3HV29J2X37f//2jmSo/+HV7f9597e/TkCaMf5f6iVOvWUr2iuS/7Wf/a5v9w9B4Bc4xqjEGwTB2C1ttZztb+z4QZHFMensnfHPSI9ZWUHRceY5DR/9t//6w80NJTAHnoxj6IHQA07r2R35rhHefW5OLO4OCelX8mC7PaZoVQFJFp5ibGTeztHGtPvkBlMKlKgESjMy1JgEpCOZj3lTM+mHd2wjoPt2cwo23WiHNQIZ+14UbBPkp1F7QQZgFX68TG5u1mDfT9j3+f3zyzJfhTrOUOWjXTQSQJetDdjp2IvkXyEmb0Nt8gJ3KyvzvVAa6X1UVh1pK45uFJGS28eebep5PaFuEuiWSrKTpqEL9k0mgm2GSVJQh2n+ug2KKK9GReCfSHv9Ow6qQbNCQ9Jts028QuHYn9KAfumTwX1VT58H6up9P9caQlQhUH6NjElRSgZatGE/R8qzJKr8fUFaYTLxZy/PnkFESk8XBjg/V/YT/qKqopUzvt3e/oBy1hmun+6APo+ThqwPGPaJP/20Avfj4wL7//yf19NJsAP+B1SkUXooNyiOz2D6jp4dqz2ngByHKK2iYDww4RyucJoJBa5fry/PIYOGSKI/mn29Yecd/aFGn6A7zHpMVCQbOtavUHHA1ZR/IdhsVHqZkG9+0RybWmqojqdkN1HRfOeefDowvkzIN780w+PL8PrFKiK4Q2QihX5/Sb7/RXm4PKPo2z2pmj7oUgN9WVbhL6qttAA/zzXE0BN8S212LUi54QaWxOu+L/dpdll/exZBC+MZJmv423plqW1r/WmHd/mv7Jt1zeRWjZFd5j3x5b82353JNs4U6dhnsXO8/GhdfnUt41KLjk2W54uXe/rbZf/bugZaTZiOtcQz/Mt9+/vZrLa6QK36J56hX+5pgEsW4LILsHK1XF+ijgW/jZU7QHt/owlaXFJdDvmtJoW/jLMQbHlt1XxJ1VIRW1ScLSlekskUDspf6K8b9s81tLTrXH792U9QPlb1/zR4X7+7/IDyX/7pv3387cun3774b959/u/eP/23T58//u+3r7/QYwD/fcMiK2iu99E2ESkZzfr2VG5zpDfLxyOJ0badXSs1M1BUBlql/DIJkun6hzSOJI+l8afHg7UqEkn6pj7axExfRjfb2iRhtanPN4XMbQrbmNoc0tNm0LTRFxGnNhsATkLXgTbUqJusOuIiJsn59s3LvRMpCL9PcFkSu13GOD1Ux1+mZyZcZw+d0upk0DD8f2WRfhZFqNjgh5w1JksNybu3dBL4sV1D0LLN3J76+qg2+kWzpd5m9/3zzbPN9VSsIEJTPlAYsgM4KP6txMV5kqXax2k34f8af395eQgWpg5q0dPskq4JXBYPjwTnQJ+SnvbcZomlx3CAuyzZEMPVEFNb6CP50MFdPkTV8ZINxNft/JoxkqRl1YULoiI4xagIcY7TEKfBk9kO07eTopSU1HA2oFXfHzLr+fiNgA3Wf4Ks6cO2DXQc7mN00GySnbRcVqZXHL4MU75iun/2mokK+/Tdz39+TGKKW1/8IMjXmyumnpSZjLrrJV/99uUvlz9+vfhzDdBOdLpTdadgU58F3JS4OuWbEO/RKa5ucVWxXdfm5vuGHfcj0QhAjovq6TYgf/9CPf43MyfPnabX7OjrpzrYJ1LLf2X5pyxtaNKcRGfZf1vh/E/EoKPPKxnZPCkOrXwKGllmhp16nmnWNXgVY+zrYRMUQXv+OihqxsZFYtfYfeV5ehhXlYFrlHEOXnx/cfvuw6f3716/+/Jv/u2X3968+zi4lXHx8uLvXy+aJH+9ePmVfPz69aJE95iUiSy4+xdURNSza0m/fkn/oAHo/5GWIY9IqPDufRbUGw7NDy/bfxxwcJf5ZXjnP2MD3+br79t/0MugH/N5vPESQ/PlP+o/SOyLN3U11dSrxdZpNE5lq/cfJAtqEHqIqSQW//e/00hNhhIgmqHfdwWLXfKhKWvXxmZFhITNiugQkflAF5h921QI8sX19+wF2Yo0q+TT5fX2x+vti6sfn23/8b0eeRn73aH0jRn3zbPnL15sn9+8sOI+GnA/215tr549v35mwNzdnvJJtqM4OxgpuLx+/sOz5z/9+NOLG1UNzd3wXUX/wb28v6HNn4mWn15cbV88v/rpSlPL1CEN1dHdz2sdkWrruSYF8vrH7Q/Klmlzh2kJd2bFkVSEH65urn/6yZTVJKk/vHjx4ofnz37Y/uM/Lv7x/wG5CNRI=END_SIMPLICITY_STUDIO_METADATA
