nodes:
  - name: ble_pd_804B50549A83
    namespace: mqtt_parse
    remappings:
      input_topic: position/ble_pd_804B50549A83
      output_topic_position: ros/position/ble_pd_804B50549A83
      output_topic_angle: ros/compound_angle/ble_pd_804B50549A83
  - name: ble_pd_804B5056BAA0
    namespace: mqtt_parse
    remappings:
      input_topic: position/ble_pd_804B5056BAA0
      output_topic_position: ros/position/ble_pd_804B5056BAA0
      output_topic_angle: ros/compound_angle/ble_pd_804B5056BAA0
  - name: ble_pd_60A423C98862
    namespace: mqtt_parse
    remappings:
      input_topic: position/ble_pd_60A423C98862
      output_topic_position: ros/position/ble_pd_60A423C98862
      output_topic_angle: ros/compound_angle/ble_pd_60A423C98862
  - name: ble_pd_60A423C997C2
    namespace: mqtt_parse
    remappings:
      input_topic: position/ble_pd_60A423C997C2
      output_topic_position: ros/position/ble_pd_60A423C997C2
      output_topic_angle: ros/compound_angle/ble_pd_60A423C997C2
  - name: ble_pd_842E1431BC70
    namespace: mqtt_parse
    remappings:
      input_topic: position/ble_pd_842E1431BC70
      output_topic_position: ros/position/ble_pd_842E1431BC70
      output_topic_angle: ros/compound_angle/ble_pd_842E1431BC70
  
